// MCU 映画データ
// release: 全米公開日 / chrono: 作中の時系列順（Disney+ の時系列順を参考にした目安）
// tmdb / poster: TMDB の作品ID とポスター画像URL（日本語版）
// branch: true の作品は別ユニバース。タイムラインから分岐して表示
const MOVIES = [
  { id: "captain-america-tfa", tmdb: 1771, poster: "https://media.themoviedb.org/t/p/w500/2YEbVbf4pSRv0o5T47V2typraZu.jpg",
    title: "キャプテン・アメリカ/ザ・ファースト・アベンジャー", en: "Captain America: The First Avenger", release: "2011-07-22", phase: 1, chrono: 1, era: "1943〜1945年",
    desc: "第二次世界大戦中、虚弱な青年スティーブ・ロジャースは超人血清によって“キャプテン・アメリカ”となり、ナチスの科学部門ヒドラとレッドスカルに立ち向かう。" },
  { id: "captain-marvel", tmdb: 299537, poster: "https://media.themoviedb.org/t/p/w500/bKFQqlpD1M7MnMeaIyUIYiAIdd9.jpg",
    title: "キャプテン・マーベル", en: "Captain Marvel", release: "2019-03-08", phase: 3, chrono: 2, era: "1995年",
    desc: "記憶を失ったクリー帝国の戦士ヴァースが1995年の地球に墜落。若きニック・フューリーと共に、自らの過去とスクラルとの戦争の真実に迫る。" },
  { id: "iron-man", tmdb: 1726, poster: "https://media.themoviedb.org/t/p/w500/gZnH9qyt45WblCc9tEKlEXVjSKA.jpg",
    title: "アイアンマン", en: "Iron Man", release: "2008-05-02", phase: 1, chrono: 3, era: "2008年",
    desc: "天才発明家で兵器企業の社長トニー・スタークは、テロ組織に拉致されたことをきっかけにパワードスーツを開発し、ヒーロー“アイアンマン”となる。" },
  { id: "iron-man-2", tmdb: 10138, poster: "https://media.themoviedb.org/t/p/w500/mj12FOks34aSc7CXL8BpEFHXgrI.jpg",
    title: "アイアンマン2", en: "Iron Man 2", release: "2010-05-07", phase: 1, chrono: 4, era: "2010年",
    desc: "正体を公表したトニーは、体を蝕むアークリアクターの毒性と、父への復讐に燃えるイワン・ヴァンコの脅威に同時に直面する。" },
  { id: "incredible-hulk", tmdb: 1724, poster: "https://media.themoviedb.org/t/p/w500/p83fuvPHucZ1JO2EZ0bFjTlXf1f.jpg",
    title: "インクレディブル・ハルク", en: "The Incredible Hulk", release: "2008-06-13", phase: 1, chrono: 5, era: "2010年頃",
    desc: "ガンマ線の影響で怒ると緑の巨人に変身してしまう科学者ブルース・バナー。治療法を探しながら、軍の追跡と怪物アボミネーションに立ち向かう。" },
  { id: "thor", tmdb: 10195, poster: "https://media.themoviedb.org/t/p/w500/2xUDJQs4kGKeLszy9E9nD19DCLA.jpg",
    title: "マイティ・ソー", en: "Thor", release: "2011-05-06", phase: 1, chrono: 6, era: "2010年頃",
    desc: "傲慢さゆえにアスガルドを追放され、力を失って地球に落とされた雷神ソー。人間との出会いを通じて真の王としての資質に目覚めていく。" },
  { id: "avengers", tmdb: 24428, poster: "https://media.themoviedb.org/t/p/w500/l1SWn7SdwvAowNfC4ojV2B9LDgs.jpg",
    title: "アベンジャーズ", en: "The Avengers", release: "2012-05-04", phase: 1, chrono: 7, era: "2012年",
    desc: "四次元キューブを奪い地球侵略を企むロキに対抗するため、S.H.I.E.L.D.はヒーローたちを集結させる。最強チーム“アベンジャーズ”誕生の物語。" },
  { id: "iron-man-3", tmdb: 68721, poster: "https://media.themoviedb.org/t/p/w500/cipMgzDMOSXygrXyCXVahNGQ1SK.jpg",
    title: "アイアンマン3", en: "Iron Man 3", release: "2013-05-03", phase: 2, chrono: 8, era: "2012年末",
    desc: "ニューヨーク決戦の後遺症に苦しむトニー。謎のテロリスト“マンダリン”に全てを奪われ、スーツに頼らず自分自身の力で戦うことになる。" },
  { id: "thor-tdw", tmdb: 76338, poster: "https://media.themoviedb.org/t/p/w500/egWwgHwt8L3sukKBPT9UuOC1JPQ.jpg",
    title: "マイティ・ソー/ダーク・ワールド", en: "Thor: The Dark World", release: "2013-11-08", phase: 2, chrono: 9, era: "2013年",
    desc: "宇宙を闇に戻そうとするダークエルフのマレキスが、強大な力“エーテル”を狙って復活。ソーは囚われの弟ロキと手を組む。" },
  { id: "captain-america-ws", tmdb: 100402, poster: "https://media.themoviedb.org/t/p/w500/npB83Gapjes4zsDMgeaMOp8xOgy.jpg",
    title: "キャプテン・アメリカ/ウィンター・ソルジャー", en: "Captain America: The Winter Soldier", release: "2014-04-04", phase: 2, chrono: 10, era: "2014年",
    desc: "S.H.I.E.L.D.内部に潜む陰謀に気づいたスティーブ。謎の暗殺者ウィンター・ソルジャーの正体は、死んだはずの親友バッキーだった。" },
  { id: "gotg", tmdb: 118340, poster: "https://media.themoviedb.org/t/p/w500/HZ9wW4KbX73rR5PQpgsuOkCU99.jpg",
    title: "ガーディアンズ・オブ・ギャラクシー", en: "Guardians of the Galaxy", release: "2014-08-01", phase: 2, chrono: 11, era: "2014年",
    desc: "宇宙のトレジャーハンター、ピーター・クイルが盗んだオーブを巡り、ならず者たちが寄せ集めのチームを結成。銀河を救う戦いに挑む。" },
  { id: "gotg2", tmdb: 283995, poster: "https://media.themoviedb.org/t/p/w500/nXguM4n72qP4o3qFVTEWZ33pjpB.jpg",
    title: "ガーディアンズ・オブ・ギャラクシー：リミックス", en: "Guardians of the Galaxy Vol. 2", release: "2017-05-05", phase: 3, chrono: 12, era: "2014年",
    desc: "ピーターの前に、実の父を名乗る謎の男エゴが現れる。家族とは何かを問いながら、ガーディアンズは新たな危機に立ち向かう。" },
  { id: "avengers-aou", tmdb: 99861, poster: "https://media.themoviedb.org/t/p/w500/jSaRZoFY8gAioBO9nMnSGA3mjl6.jpg",
    title: "アベンジャーズ/エイジ・オブ・ウルトロン", en: "Avengers: Age of Ultron", release: "2015-05-01", phase: 2, chrono: 13, era: "2015年",
    desc: "トニーが平和維持のために生み出した人工知能ウルトロンが暴走し、人類滅亡を企てる。アベンジャーズは自らが生んだ脅威と戦う。" },
  { id: "ant-man", tmdb: 102899, poster: "https://media.themoviedb.org/t/p/w500/7aqgrZYaRVCVsn11B6dXmxiXprn.jpg",
    title: "アントマン", en: "Ant-Man", release: "2015-07-17", phase: 2, chrono: 14, era: "2015年",
    desc: "前科者のスコット・ラングは、ハンク・ピム博士から体を縮める特殊スーツを託され、技術の悪用を防ぐための潜入作戦に挑む。" },
  { id: "captain-america-cw", tmdb: 271110, poster: "https://media.themoviedb.org/t/p/w500/qCZnPrC5NGjnO7uTqCD5JkCBALQ.jpg",
    title: "シビル・ウォー/キャプテン・アメリカ", en: "Captain America: Civil War", release: "2016-05-06", phase: 3, chrono: 15, era: "2016年",
    desc: "ヒーローを国連の管理下に置く“ソコヴィア協定”を巡り、アベンジャーズはアイアンマン派とキャプテン・アメリカ派に分裂する。" },
  { id: "black-widow", tmdb: 497698, poster: "https://media.themoviedb.org/t/p/w500/5qJiKpvTWM0uj2S5tyjtWnMl1A5.jpg",
    title: "ブラック・ウィドウ", en: "Black Widow", release: "2021-07-09", phase: 4, chrono: 16, era: "2016年",
    desc: "シビル・ウォー後、逃亡中のナターシャ・ロマノフ。かつての“家族”と再会し、自らを暗殺者に育てた組織“レッドルーム”と決着をつける。" },
  { id: "black-panther", tmdb: 284054, poster: "https://media.themoviedb.org/t/p/w500/teEs4qQUKzxfYB7hDCZnIBzRYmd.jpg",
    title: "ブラックパンサー", en: "Black Panther", release: "2018-02-16", phase: 3, chrono: 17, era: "2016年",
    desc: "父の死を受け、超文明国家ワカンダの王位を継いだティ・チャラ。王座を狙う謎の男キルモンガーの出現により、国の在り方が揺らぐ。" },
  { id: "spider-man-hc", tmdb: 315635, poster: "https://media.themoviedb.org/t/p/w500/x4uMWPwYUljcc6LWJSZNq19HryO.jpg",
    title: "スパイダーマン：ホームカミング", en: "Spider-Man: Homecoming", release: "2017-07-07", phase: 3, chrono: 18, era: "2016年",
    desc: "トニーに認められたい高校生ピーター・パーカー。アベンジャーズ入りを夢見ながら、危険な武器を売りさばくヴァルチャーに挑む。" },
  { id: "doctor-strange", tmdb: 284052, poster: "https://media.themoviedb.org/t/p/w500/u3IVExJVyFEiBW4xtIjQhWFuO38.jpg",
    title: "ドクター・ストレンジ", en: "Doctor Strange", release: "2016-11-04", phase: 3, chrono: 19, era: "2016〜2017年",
    desc: "事故で両手の機能を失った天才外科医スティーヴン・ストレンジ。治療法を求めて辿り着いたカトマンズで、魔術の世界に足を踏み入れる。" },
  { id: "thor-ragnarok", tmdb: 284053, poster: "https://media.themoviedb.org/t/p/w500/22v9TpnY5doZg6muPKZTaHVmKmi.jpg",
    title: "マイティ・ソー バトルロイヤル", en: "Thor: Ragnarok", release: "2017-11-03", phase: 3, chrono: 20, era: "2017年",
    desc: "死の女神ヘラによってハンマーを砕かれ、辺境の惑星に飛ばされたソー。闘技場で再会したハルクらと共にアスガルド滅亡の危機に挑む。" },
  { id: "ant-man-wasp", tmdb: 363088, poster: "https://media.themoviedb.org/t/p/w500/v357KzeDp6eKHDWxUOHODbbf2s5.jpg",
    title: "アントマン＆ワスプ", en: "Ant-Man and the Wasp", release: "2018-07-06", phase: 3, chrono: 21, era: "2018年",
    desc: "自宅軟禁中のスコットは、量子世界に囚われたジャネットを救うため、ホープ＝ワスプと再びタッグを組む。謎の存在ゴーストが立ちはだかる。" },
  { id: "avengers-iw", tmdb: 299536, poster: "https://media.themoviedb.org/t/p/w500/4szrEPRLfw1iqk30tWywoL1uEqG.jpg",
    title: "アベンジャーズ/インフィニティ・ウォー", en: "Avengers: Infinity War", release: "2018-04-27", phase: 3, chrono: 22, era: "2018年",
    desc: "6つのインフィニティ・ストーンを集め、全宇宙の生命の半分を消し去ろうとするサノス。ヒーローたちは総力を結集して最強の敵に挑む。" },
  { id: "avengers-endgame", tmdb: 299534, poster: "https://media.themoviedb.org/t/p/w500/uNWEDJzeH8VLHrs2iHkosYp2Y6W.jpg",
    title: "アベンジャーズ/エンドゲーム", en: "Avengers: Endgame", release: "2019-04-26", phase: 3, chrono: 23, era: "2018〜2023年",
    desc: "サノスの指パッチンから5年。残されたヒーローたちは、失われた仲間を取り戻すため、時間を超えた最後の作戦に全てを懸ける。" },
  { id: "shang-chi", tmdb: 566525, poster: "https://media.themoviedb.org/t/p/w500/gKZpP4chV7t2ECQZRP0oLBHfPek.jpg",
    title: "シャン・チー/テン・リングスの伝説", en: "Shang-Chi and the Legend of the Ten Rings", release: "2021-09-03", phase: 4, chrono: 24, era: "2024年",
    desc: "サンフランシスコで平凡に暮らすシャン・チー。だが、伝説の腕輪“テン・リングス”を操る父ウェンウーが、彼を過去の因縁へと引き戻す。" },
  { id: "eternals", tmdb: 524434, poster: "https://media.themoviedb.org/t/p/w500/15CiNXLhKI1Mn2paxit9Jei60S6.jpg",
    title: "エターナルズ", en: "Eternals", release: "2021-11-05", phase: 4, chrono: 25, era: "2024年",
    desc: "7000年にわたり人類を陰から見守ってきた不死の種族エターナルズ。地球に迫る滅亡の危機を前に、彼らは再び集結する。" },
  { id: "spider-man-ffh", tmdb: 429617, poster: "https://media.themoviedb.org/t/p/w500/tUzyW3leKzGeIcsMWld6cYhcO4b.jpg",
    title: "スパイダーマン：ファー・フロム・ホーム", en: "Spider-Man: Far From Home", release: "2019-07-02", phase: 3, chrono: 26, era: "2024年",
    desc: "トニー亡き後、ヨーロッパ旅行に出かけたピーター。そこで出会った謎のヒーロー、ミステリオと共に怪物“エレメンタルズ”と戦う。" },
  { id: "spider-man-nwh", tmdb: 634649, poster: "https://media.themoviedb.org/t/p/w500/j2vwjzuofol93OcSn8xAHJiTEoz.jpg",
    title: "スパイダーマン：ノー・ウェイ・ホーム", en: "Spider-Man: No Way Home", release: "2021-12-17", phase: 4, chrono: 27, era: "2024年",
    desc: "正体が世界に知られてしまったピーター。ドクター・ストレンジの呪文が失敗し、マルチバースから過去のヴィランたちが現れてしまう。" },
  { id: "doctor-strange-mom", tmdb: 453395, poster: "https://media.themoviedb.org/t/p/w500/uIBieATCKY8fnnCnDYoIffUMqP5.jpg",
    title: "ドクター・ストレンジ/マルチバース・オブ・マッドネス", en: "Doctor Strange in the Multiverse of Madness", release: "2022-05-06", phase: 4, chrono: 28, era: "2024年",
    desc: "マルチバースを移動できる少女アメリカ・チャベスを守るため、ストレンジは禁断の魔術に手を染めた“あの人物”と対峙する。" },
  { id: "thor-lat", tmdb: 616037, poster: "https://media.themoviedb.org/t/p/w500/pxhxlAkUxfLAb3dPBXcEEsSlncT.jpg",
    title: "ソー：ラブ＆サンダー", en: "Thor: Love and Thunder", release: "2022-07-08", phase: 4, chrono: 29, era: "2025年",
    desc: "神々を抹殺する“神殺しのゴア”が出現。ソーは、ムジョルニアを手にした元恋人ジェーン＝マイティ・ソーらと共に戦う。" },
  { id: "black-panther-wf", tmdb: 505642, poster: "https://media.themoviedb.org/t/p/w500/cB1kPUw8brtZRbXSKp1gdkWhd9q.jpg",
    title: "ブラックパンサー/ワカンダ・フォーエバー", en: "Black Panther: Wakanda Forever", release: "2022-11-11", phase: 4, chrono: 30, era: "2025年",
    desc: "国王ティ・チャラを失ったワカンダ。悲しみの中、海底王国タロカンの王ネイモアの脅威が迫り、残された者たちが国を守るために立ち上がる。" },
  { id: "ant-man-quantumania", tmdb: 640146, poster: "https://media.themoviedb.org/t/p/w500/sF8z34NGwy1qGr3kWYIGgWO8hYl.jpg",
    title: "アントマン＆ワスプ：クアントマニア", en: "Ant-Man and the Wasp: Quantumania", release: "2023-02-17", phase: 5, chrono: 31, era: "2025年",
    desc: "量子世界に引きずり込まれたスコットたち。そこで待っていたのは、マルチバースを揺るがす征服者カーンだった。" },
  { id: "gotg3", tmdb: 447365, poster: "https://media.themoviedb.org/t/p/w500/waTQqjV1dvGlbCAhN2VAIierdev.jpg",
    title: "ガーディアンズ・オブ・ギャラクシー：VOLUME 3", en: "Guardians of the Galaxy Vol. 3", release: "2023-05-05", phase: 5, chrono: 32, era: "2026年",
    desc: "瀕死の重傷を負ったロケットを救うため、ガーディアンズは彼の悲しい過去と、彼を生み出したハイ・エボリューショナリーに迫る。" },
  { id: "the-marvels", tmdb: 609681, poster: "https://media.themoviedb.org/t/p/w500/b6ipQGmVXqeyWLTbMxKCOWCuv1m.jpg",
    title: "マーベルズ", en: "The Marvels", release: "2023-11-10", phase: 5, chrono: 33, era: "2026年",
    desc: "キャロル、モニカ、カマラの3人の能力が謎の現象で絡み合い、使うたびに居場所が入れ替わってしまう。3人は即席チームとして宇宙の危機に挑む。" },
  { id: "deadpool-wolverine", tmdb: 533535, poster: "https://media.themoviedb.org/t/p/w500/3kQ7wDhrAd02fEwSBGQ1ZtCJDze.jpg",
    title: "デッドプール＆ウルヴァリン", en: "Deadpool & Wolverine", release: "2024-07-26", phase: 5, chrono: 34, branch: true, era: "2024年頃（別ユニバース）",
    desc: "自分の世界の消滅を知ったデッドプールは、別のユニバースから“最悪のウルヴァリン”を連れ出し、時間変異取締局TVAを巻き込む大騒動を起こす。" },
  { id: "captain-america-bnw", tmdb: 822119, poster: "https://media.themoviedb.org/t/p/w500/bvSaHm4mqNP20B0C00XRh0PeNHd.jpg",
    title: "キャプテン・アメリカ：ブレイブ・ニュー・ワールド", en: "Captain America: Brave New World", release: "2025-02-14", phase: 5, chrono: 35, era: "2027年頃",
    desc: "新たなキャプテン・アメリカとなったサム・ウィルソン。ロス大統領との会談をきっかけに、世界を揺るがす国際的陰謀に巻き込まれる。" },
  { id: "thunderbolts", tmdb: 986056, poster: "https://media.themoviedb.org/t/p/w500/q9X2CbexqGwkpkVI8ORWkQ5vltj.jpg",
    title: "サンダーボルツ*", en: "Thunderbolts*", release: "2025-05-02", phase: 5, chrono: 36, era: "2027年頃",
    desc: "罠にはめられたエレーナら“はみ出し者”たちが、思いがけず即席チームを結成。過去に傷を抱えた彼らが、自分自身と向き合う。" },
  { id: "fantastic-four", tmdb: 617126, poster: "https://media.themoviedb.org/t/p/w500/7AuLDxII9LcORX4dFa0QeXTqjyC.jpg",
    title: "ファンタスティック４：ファースト・ステップ", en: "The Fantastic Four: First Steps", release: "2025-07-25", phase: 6, chrono: 37, branch: true, era: "1960年代風の別地球（Earth-828）",
    desc: "レトロフューチャーな世界で活躍するヒーローチーム“ファンタスティック４”。惑星を喰らう存在ギャラクタスと、その使者シルバーサーファーが地球に迫る。" },
  { id: "spider-man-bnd", tmdb: 969681, poster: "https://media.themoviedb.org/t/p/w500/hvbs76wGMZYqJSvaRps5jDzHUhN.jpg",
    title: "スパイダーマン：ブランド・ニュー・デイ", en: "Spider-Man: Brand New Day", release: "2026-07-31", phase: 6, chrono: 38, era: "2027年頃",
    desc: "世界中の人々から存在を忘れられたピーター・パーカー。孤独な“親愛なる隣人”として、新たな日々を歩み始める。" },
  { id: "avengers-doomsday", tmdb: 1003596, poster: "https://media.themoviedb.org/t/p/w500/axD1jIfE2Is83vDKyTb1CnZ2EBt.jpg",
    title: "アベンジャーズ/ドゥームズデイ", en: "Avengers: Doomsday", release: "2026-12-18", phase: 6, chrono: 39, era: "未発表",
    desc: "ドクター・ドゥームが登場するアベンジャーズ最新作。マルチバース・サーガのクライマックスへ向けた戦いが始まる。（公開予定）" },
];
